/**
 * The 64 districts of Bangladesh, in the spelling the delivery_zones rows use.
 *
 * Zone resolution is case-insensitive and trims whitespace, but it matches on
 * the district STRING, so these names must stay in step with the `districts`
 * arrays seeded in migration 0013. Anything not listed in a zone falls through
 * to the fallback zone, which is why an unfamiliar spelling is safe rather than
 * fatal — it just costs the customer the higher nationwide rate.
 */
export const BD_DISTRICTS = [
  "Dhaka",
  "Gazipur",
  "Narayanganj",
  "Narsingdi",
  "Munshiganj",
  "Manikganj",
  "Savar",
  "Keraniganj",
  "Chattogram",
  "Cox's Bazar",
  "Cumilla",
  "Brahmanbaria",
  "Chandpur",
  "Feni",
  "Lakshmipur",
  "Noakhali",
  "Khagrachhari",
  "Rangamati",
  "Bandarban",
  "Sylhet",
  "Moulvibazar",
  "Habiganj",
  "Sunamganj",
  "Khulna",
  "Bagerhat",
  "Satkhira",
  "Jashore",
  "Jhenaidah",
  "Magura",
  "Narail",
  "Kushtia",
  "Chuadanga",
  "Meherpur",
  "Rajshahi",
  "Bogura",
  "Pabna",
  "Sirajganj",
  "Natore",
  "Naogaon",
  "Joypurhat",
  "Chapainawabganj",
  "Rangpur",
  "Dinajpur",
  "Thakurgaon",
  "Panchagarh",
  "Nilphamari",
  "Lalmonirhat",
  "Kurigram",
  "Gaibandha",
  "Barishal",
  "Bhola",
  "Patuakhali",
  "Pirojpur",
  "Barguna",
  "Jhalokathi",
  "Mymensingh",
  "Jamalpur",
  "Netrokona",
  "Sherpur",
  "Tangail",
  "Kishoreganj",
  "Faridpur",
  "Gopalganj",
  "Madaripur",
  "Rajbari",
  "Shariatpur",
] as const;

export type BdDistrict = (typeof BD_DISTRICTS)[number];
